[package]
name = "imgtag"
version = "0.1.0"
authors = ["Eugene Lebedev <duke.tougu@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
clap = "2.33"

rexif = "0.5"

chrono = "0.4"

log = "0.4"
log4rs = "0.8"
